[package]
name = "devenv"
version = "0.1.0"
authors = ["Guillem Castro <guillemcastro4@gmail.com>"]
edition = "2018"

[dependencies]
devenv-core = { path = "../devenv-core" }
log = "0.4.8"
simple_logger = "1.11.0"
clap = "3.0.0-beta.1"
toml = "0.5.6"
